# Generated by Django 5.0.4 on 2024-05-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfo',
            name='other_info',
            field=models.TextField(blank=True),
        ),
    ]
