# Generated by Django 5.0.4 on 2024-05-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcv', '0002_alter_cvinfo_other_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvinfo',
            name='job_role',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
